install.packages("swirl")
library(swirl)
library(swirl)
Hi! Type swirl()
Hi! Type swirl() '!' in "Hi!"
swirl()
1
2
swirl_options()
swirl_options()
help
swirl_options()
swirl()
library(readr)
epa_http <- read_table("C:/Data Science/epa-http/epa-http.csv",
col_names = FALSE)
View(epa_http)
DFPRINCIPAL <- epa_http
colnames(DFPRINCIPAL) <- c("IP", "TIEMPO", "TIPOPET", "URL", "PROTOCOLO", "CODRESPUESTA", "BYTERESPUESTA")
dim(DFPRINCIPAL)
DFPRINCIPAL$BYTERESPUESTA <- as.numeric(DFPRINCIPAL$BYTERESPUESTA)
DFPRINCIPAL$BYTERESPUESTA <- as.numeric(DFPRINCIPAL$BYTERESPUESTA)
DFPRINCIPAL$BYTERESPUESTA <- ifelse(is.na(DFPRINCIPAL$BYTERESPUESTA),0,DFPRINCIPAL$BYTERESPUESTA)
mean(DFPRINCIPAL$BYTERESPUESTA)
View(DFPRINCIPAL)
SUBDFPRINCIPAL_EDU <-DFPRINCIPAL[grep("\\.edu", DFPRINCIPAL$IP), ]
View(SUBDFPRINCIPAL_EDU)
nrow(SUBDFPRINCIPAL_EDU)
DFTIPOGET <- DFPRINCIPAL[grepl("GET", DFPRINCIPAL$TIPOPET),
DFTIPOGET <- DFPRINCIPAL[grepl("GET", DFPRINCIPAL$TIPOPET)
DFPRINCIPALTIPOGET <- DFPRINCIPAL[grepl("GET", DFPRINCIPAL$TIPOPET) ]
DFPRINCIPALTIPOGET <- DFPRINCIPAL[grepl("GET", DFPRINCIPAL$TIPOPET), ]
View(DFPRINCIPALTIPOGET)
VECTORHORA <- substr(DFPRINCIPALTIPOGET$TIEMPO,5,6)
VECTORHORAUP <- table(VECTORHORA)
VECTORHORAFINAL <-sort(VECTORHORAUP),decreasing=TRUE)
VECTORHORAFINAL <-sort(VECTORHORAUP,decreasing=TRUE)
View(VECTORHORAFINAL)
save.image("C:/Data Science/Práctica 1/Práctica 1.RData")
View(SUBDFPRINCIPAL_EDU)
SUBDFPRINCIPAL_EDU <-DFPRINCIPAL[grep("\\.edu", DFPRINCIPAL$IP), ]
SUBDFPRINCIPAL_TXT <- SUBDFPRINCIPAL_EDU[grepl("\\.txt", SUBDFPRINCIPAL_EDU$URL), ]
sum(SUBDFPRINCIPAL_TXT$BYTERESPUESTA)
DFPRINCIPALURL <- DFPRINCIPAL[grepl("^/$", DFPRINCIPAL$URL), ]
nrow(DFPRINCIPAL$URL)
nrow(DFPRINCIPALURL)
DFPRINCIPALURL <- DFPRINCIPAL[grepl("^/$", DFPRINCIPAL$URL), ]
nrow(DFPRINCIPALURL)
DFPRINCIPALHTTP <- DFPRINCIPAL[!grepl("HTTP/0.2", DFPRINCIPAL$PROTOCOLO),]
View(DFPRINCIPALHTTP)
DFPRINCIPALHTTP <- DFPRINCIPAL[!grepl("HTTP/0.2", DFPRINCIPAL$PROTOCOLO),]
View(DFPRINCIPALHTTP)
nrow(DFPRINCIPALHTTP)
save.image("C:/Data Science/Práctica 1/Práctica 1.RData")
